
version: 2

build:
  image: "ubuntu-22.04"  # The image to use for the build environment, can change it to match the project's needs
  os: "ubuntu-22.04"    # The OS for build environment

# Specify the default branch and the location of docs folder
sphinx:
  configuration: docs/source/conf.py  # Path to your Sphinx configuration file

python:
  version: 3.8  
