
version: 2

# Build settings
build:
  image: "ubuntu-22.04"
  os: "ubuntu-22.04"
  tools:
    sphinx:
      version: "5.0"  # specify the version of Sphinx used, adjust if needed

sphinx:
  configuration: docs/source/conf.py  # Path to Sphinx configuration file

# Optional: Set the Python version for the build environment
python:
  version: 3.8  # Use the appropriate Python version

