# to tell read the doc what specific setting to use for this project
version: 2

# Build settings
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"  # specify the Python version required to run Sphinx

# Specify the location of your Sphinx configuration file
sphinx:
  configuration: docs/source/conf.py  # Path to Sphinx configuration file






