
version: 2

# Build settings
build:
  tools:
    python: "3.8"  # specify the Python version

# Specify the location of your Sphinx configuration file
sphinx:
  configuration: docs/source/conf.py  # path to your Sphinx configuration file




